# Generated by Django 3.0.6 on 2020-07-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IFSC', models.CharField(max_length=11)),
                ('Branch', models.CharField(max_length=75)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Bank_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybank.Banks')),
            ],
        ),
    ]
