# Generated by Django 3.0.4 on 2020-07-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0002_auto_20200702_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='Bank_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybank.Banks'),
        ),
    ]
